// <auto-generated />
namespace Bakaleja__Курсовой_прект_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addShop : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addShop));
        
        string IMigrationMetadata.Id
        {
            get { return "202303041027293_addShop"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
